### ISSUE TITLE
Cópia em arquivos ainda não salvos em disco

### ISSUE THREAD

**Issue by jeisoncp** [marcelovsantos/atom-copy-highlighted#1]
[Enter steps to reproduce:]

1. Abrir um novo arquivo e não salvá-lo
2. Digitar algum código e selecioná-lo
3. Executar copy-highlighted

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [copy-highlighted](https://github.com/marcelovsantos/atom-copy-highlighted) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At /home/jeison/.atom/packages/copy-highlighted/lib/copy-highlighted.js:38

TypeError: Cannot read property 'path' of null
    at Object.copy (/packages/copy-highlighted/lib/copy-highlighted.js:38:41)
    at HTMLElement.copyHighlightedCopy (/packages/copy-highlighted/lib/copy-highlighted.js:23:49)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:381:36)
    at Object.didConfirmSelection (/opt/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:144:35)
    at SelectListView.confirmSelection (/opt/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:324:26)
    at SelectListView.didClickItem (/opt/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:239:16)
    at ListItemView.onclick (/opt/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:178:39)
    at ListItemView.didClick (/opt/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:372:16)
```

### Commands

```
     -9:48.8.0 command-palette:toggle (input.hidden-input)
     -9:13.6.0 copy-highlighted:copy (input.hidden-input)
```

### Non-Core Packages

```
atom-gooey-syntax 1.0.0 
atom-ide-ui 0.5.3 
auto-indent 0.5.0 
autocomplete-modules 1.8.0 
batman-syntax 1.1.0 
copy-highlighted 0.2.0 
editorconfig 2.2.2 
file-icons 2.1.13 
git-change-marker 0.16.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
ide-php 0.6.9 
ide-typescript 0.6.2 
language-asp 1.1.0 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-git-diff 4.3.1 
multirow-tabs 0.3.3 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
project-plus 1.0.0 
Remote-FTP 1.3.1 
```

**Comment by marcelovsantos** [comment]
Fixed.

**Comment by daron4ever** [comment]
Thanks. This is such a great package.
