### ISSUE TITLE
Uncaught TypeError: Cannot read property 'buffer' of undefined

### ISSUE THREAD

**Issue by lzy-106** [marcelovsantos/atom-copy-highlighted#5]
Happens at initial use

1. Start up Atom
2. Open new Python file
3. Enter a simple line
4. Use copy highlighted

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15
**Thrown From**: [copy-highlighted](https://github.com/marcelovsantos/atom-copy-highlighted) package 0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'buffer' of undefined

```
At /Users/ast/.atom/packages/copy-highlighted/lib/copy-highlighted.js:40

TypeError: Cannot read property 'buffer' of undefined
    at Object.copy (/packages/copy-highlighted/lib/copy-highlighted.js:40:20)
    at HTMLElement.copyHighlightedCopy (/packages/copy-highlighted/lib/copy-highlighted.js:23:49)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349780)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348255)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:725974)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:733897)
    at EventEmitter.emit (events.js:194:13)
```

### Commands

```
     -0:56.2.0 core:paste (input.hidden-input)
     -0:54 core:select-all (input.hidden-input)
     -0:53.2.0 grammar-selector:show (atom-text-editor.editor.is-focused.has-selection)
     -0:50.9.0 core:confirm (input.hidden-input)
     -0:49.9.0 core:select-all (input.hidden-input)
     -0:49.6.0 core:copy (input.hidden-input)
     -0:35.7.0 styleguide:show (input.hidden-input)
     -0:27.3.0 copy-highlighted:copy (div.styleguide.pane-item.native-key-bindings)
     -0:02.1.0 core:paste (input.hidden-input)
     -0:01.4.0 core:select-all (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-simplified-chinese-menu 0.6.5 
busy-signal 2.0.1 
commit-reminder 0.1.1 
copy-highlighted 0.5.0 
gherkin-snippets 0.3.0 
intentions 1.1.5 
language-gherkin 1.0.4 
language-haml 0.32.1 
language-riscv 1.2.0 
language-tex 0.4.0 
line-number-color 0.2.0 
linter 2.3.1 
linter-pylint 2.1.1 
linter-ui-default 1.8.1 
markdown-cell-highlight 1.2.0 
mojave-dark-mode 0.4.0 
monokai 0.24.0 
python-linters 0.0.4 
```

**Comment by marcelovsantos** [comment]
Hi, save your file before use copy highlighted. Its work?
